### ISSUE TITLE
Algo for "Top" ranking needs refinement with regard to new posts

### ISSUE THREAD

**Issue by shamilovtim** [ruqqus/ruqqus#238]
When ranking a board by "Top" a brand new post gets absolutely buried to the bottom of a board (literally last place beneath all older posts). As seen on Reddit it's more typical for a new post to get ranked somewhere in between. Usually near the bottom of the first page or within the first couple of pages of a board. I think this needs a second look.

**Comment by noahmaranesi** [comment]
Happened to me too. In my case, the sorting is for "**Hot**".

I just submitted a single post to [+PopPunk](https://ruqqus.com/+PopPunk) and it goes to the bottom of the Guild that had 9 other posts (therefore now 10). The earliest post on this Guild was 8 days ago and is above the fresh post.

See: https://web.archive.org/web/20200617094039/https://ruqqus.com/+PopPunk

As of this archive, the post was submitted 18 minutes ago (however, ever since it was posted, it has remained at the bottom).

I think it would be a good idea for if there is less than 3 posts within the past 12 hours (I'm counting in for more popular Guilds too; +PopPunk only has 4 subscribers/members), that they all remain somewhat at the top, especially if it's at a positive score.

**Comment by captainmeta4** [comment]
Top is intended to be a very straightforward rank by absolute score without regard to the age of the post. Therefore, a new post that only has a couple upvotes should not rank particularly highly.

For Hot, we have had some feedback that Hot isn't favoring new content quite well enough. This is something I will change, probably later today.

**Comment by shamilovtim** [comment]
Oops it's a little easy to confuse them cause they're both 3 letter words and vaguely similar in meaning. Maybe change "hot" to "trending"?
