### ISSUE TITLE
Tips to speed ruqqus up, prevent 503s and reduce network usage.

### ISSUE THREAD

**Issue by 47773838382882828** [ruqqus/ruqqus#278]
Issue tracker is **ONLY** used for reporting bugs.

## Current Behavior
Ruqqus is extremely slow (+6 seconds), frequent 503s and there's an influx of users which is going to be very expensive.

## Possible fixes
- Browser caching
- Not loading the entire image when you go to ruqqus.com but instead a thumbnail
- Using formats like WebP or JPEG2000 instead (or converting PNG and JPG files to WebP when the user uploads them)

**Comment by shamilovtim** [comment]
I think these guys should ASAP solicit and bring in a full stack engineer that has experience scaling and load balancing web apps, tuning SQL queries and sharding databases. Ultimately if someone has never had to do this before there's no substitute for experience. Learning by trial and error while hemorrhaging users is the least efficient path toward success because a certain % of those users will never come back and are lost forever. They should out a call for help or experienced volunteers, whatever they need to do, there are tons of people willing to help.

**Comment by Known-as-X86** [comment]
I can help with that (not fulltime though). the only problem is that the application seems to be monolithic and scaling needs to be done vertically right now. very expensive. and obviously i can't know the production enviroment this app is running in so right now there's alot of guesswork in what the major bottlenecks in infrastructure are. 

some things i can actually see is using postgesql for large amounts of realtime data and that is a major bottleneck in the code. preferably you would use some pub/sub style architecture for this like kafka/rabbitmq.

And caching needs to be handled outside of the application layer / since you can offload networking load / python overhead from the application server itself to something lighter like varnish.

Hit me up on GH/mail if you want to discuss this.

**Comment by shamilovtim** [comment]
@captainmeta4 @kek7198 Are you guys open to help from the OSS community?

**Comment by sprutner** [comment]
I agree with @Known-as-X86 serious gains can be made from using

1) pub/sub architecture like Amazon SQS/Kafka/Rabbit/NSQ etc...
1) database caching using Redis with a read-through cache should help a ton.

Happy to discuss this more, I have worked on some high-scale apps in the past and these two things are KEY

**Comment by shamilovtim** [comment]
@sprutner @Known-as-X86 I believe they're using an ORM as-is so there are untuned SQL queries. It's worth looking into.

**Comment by shamilovtim** [comment]
@captainmeta4 Come on dude. What are you even doing? Same file committed 100s of times with trial and error programming. Experienced folks you're ignoring while you have nearly 100% downtime for days at a time. Completely blowing it.

**Comment by Known-as-X86** [comment]
I have already giving up on trying to contribute.

**Comment by 47773838382882828** [comment]
Why'd you give up?

**Comment by captainmeta4** [comment]
Performance has improved a lot in the last months so I'm going to go ahead and close this one. We had a lot of inefficient queries, as mentioned above, bogging down the system.
