### ISSUE TITLE
Federating Ruqqus? 

### ISSUE THREAD

**Issue by t3pfaffe** [ruqqus/ruqqus#283]
### Problem
I think the true way to achieve user freedom is to allow the platform to be as operator agnostic as possible. Obviously there must always be some censorship (removal of spam etc.) and that allows for abuse. I'm sure we are all willing to trust the current operators (as you seem to have all the right intentions to support the ideals of free speech for effective discourse) but the beautiful thing about open source software is that we have envisioned ways in which we don't have to. 

### Solution
Implementation of federation (greater ease of self hosting) and perhaps full implementation of [ActivityPub](https://github.com/w3c/activitypub). Essentially meaning that if someone is in disagreement to administration policy they can semi-easily setup their own instance. Users need not create new accounts for each of these instances as the servers can communicate between each other via open standards.

### Alternatives
The only alternative to federation is hedging trust in the benevolence of Ruqqus administration. I know [lemmy](https://github.com/LemmyNet/lemmy) exists as already trying to fulfill this but Ruqqus is much closer to having the critical mass (although still far away) needed to make the link-aggregator style algorithms work. And if ActivityPub is implmented, techincally Ruqqus and Lemmy servers can talk to each other. That sounds fun. 

Is this something that has been thought about and subsequently dismissed for various reasons? 

**Additional Note** 
Additionally I am sure we all know the consequences being a "free speech zone" on the internet where main stream ideas often still feel comfortable in their "regulated speech zones." It invites a disproportionate amount of the 'radical speech/ideolgoy' that is considered too dangerous for those regulated zones. This is often where free speech alternatives to mainstream over-regulated services fail. They invite too much of that radical ideology that they become an echo-chamber scaring away the more mainstream ideology holders. And since echo-chambers actively oppose outsiders new user growth will be negatively effected and the service will fail to reach critical mass, subsequently fail to be self sustaining, and then fizzle out. 

Perhaps with federation this is avoidable to some extent. Because you can let radicals of opposing ideologies echo-chamber themselves to their own instances. This would allow many of these radical ideologies to exist next to each other under the umbrella of 'ruqqus' that would have otherwise radically opposed each other until one won out. Its a beautiful way of streamlining the process of self determination.  

In an ideal world this would not be necessary because more mainstream ideology holders would value not having regulated speech and would move over to less regulated platforms. However I have little faith that society values free speech anymore and thus must be coaxed into it via technology that ensures their inalienable rights for them.

**Comment by 47773838382882828** [comment]
Implementing activitypub isn't really feasible right now but in the future it could be.

Here are some docs for activitypub

https://www.w3.org/TR/activitypub/

https://socialhub.activitypub.rocks/t/guide-for-new-activitypub-implementers/479

https://raw.githubusercontent.com/w3c/activitypub/gh-pages/activitypub-tutorial.txt

https://blog.joinmastodon.org/2018/06/how-to-implement-a-basic-activitypub-server/

**Comment by jfwerner** [comment]
We definitely need a strong federated social network, and I don't feel like the fediverse is growing substantially. It's all pretty dead in terms of users.
I think the problem is in the way instances are handled, people don't want a "local" timeline. The issue lies in centralizing decentral content, while still enforcing each federations rules.

A mainstream federated network would be beautiful to see. It also helps of course to spread the server costs that way.

**Comment by BurnyBoi** [comment]
Just as a somewhat-related update, Lemmy (a similar self-hosted Reddit-like application) recently got Federation over ActivityPub into beta: [lemmy-v080-release-2020-10-16](https://github.com/LemmyNet/lemmy/blob/main/RELEASES.md#lemmy-v080-release-2020-10-16) . This project seems like one to keep an eye on when implementing federation in Ruqqus, since doing so could allow Ruqqus and Lemmy instances to communicate more easily, growing the user base even more.

**Comment by t3pfaffe** [comment]
Yeah, I believe I referenced that in the original post.
