### ISSUE TITLE
I think blocking users may be broken. Any users that I have tried to block after the migration do not appear blocked in my account settings.

### ISSUE THREAD

**Issue by TheSilentKnight16** [ruqqus/ruqqus#473]
Any users that I have tried to block after the migration (not sure if that’s the cause of the problem, but it seems to be happening since then) do not appear to be blocked on my profile, and their posts and comments still appear. Although when I click the block button it says they were blocked, but they are not blocked. I’m on mobile safari if that helps.

**Comment by CrystalVulpine** [comment]
I was able to unblock users just fine. I could also block users, initially it gives an error, but when I try again it says they're already blocked and reloading the page shows that they are now listed in blocks. I also think you should be able to block users without preventing them from seeing your posts. Whenever I feel like I want to block someone I can't because that would happen if I did.

Also, hidden guilds should be hidden *everywhere*, not just on all. If you hide a guild there's a reason, because you don't want to see it.

**Comment by TheSilentKnight16** [comment]
Nvm. It works now. Idk why it wasn’t working for me before. False bug; sorry for waste of time.
