### ISSUE TITLE
Account is suspended but I still have all functionality/privileges of a normal end user 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [ruqqus/ruqqus#484]
text

**Comment by DGKSK8LIFE** [comment]
ah; so it looks like I can view posts and updoot, but no commenting. Idk if this is desired or not @captainmeta4

**Comment by SuperLeaf1995** [comment]
b r e u h

**Comment by CrystalVulpine** [comment]
That's not a big deal. The bigger issue is the admins banning people just because they have hot water between them. Ruqqus is already becoming reddit.

**Comment by DGKSK8LIFE** [comment]
@CrystalVulpine based and true

**Comment by SuperLeaf1995** [comment]
@CrystalVulpine very true

**Comment by devongalat** [comment]
> That's not a big deal. The bigger issue is the admins banning people just because they have hot water between them. Ruqqus is already becoming reddit.

DGK was banned on Ruqqus for admin impersonation as he wrote that he was a core member of the Ruqqus admin team on his LinkedIn. AFAIK, captain asked DGK to remove it.

On Discord, he was banned because he constantly broke the rules. He had 7 warnings or so issued to him for different reasons.

Do you really think the admins ban people because there's *'hot water between them'*?

**Comment by DGKSK8LIFE** [comment]
@devongalat I removed ruqqus on my linkedin a long time ago. I forgot that I said I was ruqqus core team on my ruqqus account (I had been afk for a while) so that was suspended. I think admins are banning people unnecessarily/doing it to an extent where it impedes ruqqus' core values.

**Comment by CrystalVulpine** [comment]
@devongalat @DGKSK8LIFE is right. While the discord ban makes sense, for the site ban they just used such a petty reason to ban him for, which was probably accidental anyway, and especially considering it was a permaban. It seems clear to me that the admins just wanted to get rid of him because they thought he was annoying. This would not be the first time I've seen something like that happen either. Transparency and free speech are becoming less and less the cornerstone of ruqqus, and by now I don't even think it's the most important aspect anymore and it's already being abandoned in small ways. Ruqqus is basically just right-wing reddit now.

**Comment by DGKSK8LIFE** [comment]
@CrystalVulpine You hit the nail on the head with the last sentence. Every time I show my friends ruqqus, that's what they remark.

**Comment by captainmeta4** [comment]
Title is misleading; there is no problem here, as OP is correctly unable to post/comment. As stated in the pinned post, this is not the appropriate forum to argue account issues in.
